/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedShareRouteImport } from './routes/_authenticated/share'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as PhotosAlbumIdRouteImport } from './routes/photos.$albumId'
import { Route as RosterIndexRouteImport } from './routes/roster.index'
import { Route as RosterPlayerIdRouteImport } from './routes/roster.$playerId'
import { Route as TournamentsEventIdRouteImport } from './routes/tournaments.$eventId'
import { Route as PhotosGameEventIdRouteImport } from './routes/photos.game.$eventId'
import { Route as PhotosSeasonSeasonRouteImport } from './routes/photos.season.$season'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShareRoute = AuthenticatedShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhotosRoute,
} as any)
const PhotosAlbumIdRoute = PhotosAlbumIdRouteImport.update({
  id: '/$albumId',
  path: '/$albumId',
  getParentRoute: () => PhotosRoute,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterPlayerIdRoute = RosterPlayerIdRouteImport.update({
  id: '/roster/$playerId',
  path: '/roster/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsEventIdRoute = TournamentsEventIdRouteImport.update({
  id: '/tournaments/$eventId',
  path: '/tournaments/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosGameEventIdRoute = PhotosGameEventIdRouteImport.update({
  id: '/game/$eventId',
  path: '/game/$eventId',
  getParentRoute: () => PhotosRoute,
} as any)
const PhotosSeasonSeasonRoute = PhotosSeasonSeasonRouteImport.update({
  id: '/season/$season',
  path: '/season/$season',
  getParentRoute: () => PhotosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/photos': typeof PhotosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/share': typeof AuthenticatedShareRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/tournaments/$eventId': typeof TournamentsEventIdRoute
  '/photos/': typeof PhotosIndexRoute
  '/roster/': typeof RosterIndexRoute
  '/photos/game/$eventId': typeof PhotosGameEventIdRoute
  '/photos/season/$season': typeof PhotosSeasonSeasonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/share': typeof AuthenticatedShareRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/tournaments/$eventId': typeof TournamentsEventIdRoute
  '/photos': typeof PhotosIndexRoute
  '/roster': typeof RosterIndexRoute
  '/photos/game/$eventId': typeof PhotosGameEventIdRoute
  '/photos/season/$season': typeof PhotosSeasonSeasonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/photos': typeof PhotosRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/share': typeof AuthenticatedShareRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/photos/$albumId': typeof PhotosAlbumIdRoute
  '/roster/$playerId': typeof RosterPlayerIdRoute
  '/tournaments/$eventId': typeof TournamentsEventIdRoute
  '/photos/': typeof PhotosIndexRoute
  '/roster/': typeof RosterIndexRoute
  '/photos/game/$eventId': typeof PhotosGameEventIdRoute
  '/photos/season/$season': typeof PhotosSeasonSeasonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/photos'
    | '/reset-password'
    | '/schedule'
    | '/admin'
    | '/share'
    | '/stats'
    | '/photos/$albumId'
    | '/roster/$playerId'
    | '/tournaments/$eventId'
    | '/photos/'
    | '/roster/'
    | '/photos/game/$eventId'
    | '/photos/season/$season'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/reset-password'
    | '/schedule'
    | '/admin'
    | '/share'
    | '/stats'
    | '/photos/$albumId'
    | '/roster/$playerId'
    | '/tournaments/$eventId'
    | '/photos'
    | '/roster'
    | '/photos/game/$eventId'
    | '/photos/season/$season'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/photos'
    | '/reset-password'
    | '/schedule'
    | '/_authenticated/admin'
    | '/_authenticated/share'
    | '/_authenticated/stats'
    | '/photos/$albumId'
    | '/roster/$playerId'
    | '/tournaments/$eventId'
    | '/photos/'
    | '/roster/'
    | '/photos/game/$eventId'
    | '/photos/season/$season'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  PhotosRoute: typeof PhotosRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  RosterPlayerIdRoute: typeof RosterPlayerIdRoute
  TournamentsEventIdRoute: typeof TournamentsEventIdRoute
  RosterIndexRoute: typeof RosterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/share': {
      id: '/_authenticated/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof AuthenticatedShareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/photos/': {
      id: '/photos/'
      path: '/'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/photos/$albumId': {
      id: '/photos/$albumId'
      path: '/$albumId'
      fullPath: '/photos/$albumId'
      preLoaderRoute: typeof PhotosAlbumIdRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$playerId': {
      id: '/roster/$playerId'
      path: '/roster/$playerId'
      fullPath: '/roster/$playerId'
      preLoaderRoute: typeof RosterPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$eventId': {
      id: '/tournaments/$eventId'
      path: '/tournaments/$eventId'
      fullPath: '/tournaments/$eventId'
      preLoaderRoute: typeof TournamentsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/game/$eventId': {
      id: '/photos/game/$eventId'
      path: '/game/$eventId'
      fullPath: '/photos/game/$eventId'
      preLoaderRoute: typeof PhotosGameEventIdRouteImport
      parentRoute: typeof PhotosRoute
    }
    '/photos/season/$season': {
      id: '/photos/season/$season'
      path: '/season/$season'
      fullPath: '/photos/season/$season'
      preLoaderRoute: typeof PhotosSeasonSeasonRouteImport
      parentRoute: typeof PhotosRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedShareRoute: typeof AuthenticatedShareRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedShareRoute: AuthenticatedShareRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PhotosRouteChildren {
  PhotosAlbumIdRoute: typeof PhotosAlbumIdRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  PhotosGameEventIdRoute: typeof PhotosGameEventIdRoute
  PhotosSeasonSeasonRoute: typeof PhotosSeasonSeasonRoute
}

const PhotosRouteChildren: PhotosRouteChildren = {
  PhotosAlbumIdRoute: PhotosAlbumIdRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  PhotosGameEventIdRoute: PhotosGameEventIdRoute,
  PhotosSeasonSeasonRoute: PhotosSeasonSeasonRoute,
}

const PhotosRouteWithChildren =
  PhotosRoute._addFileChildren(PhotosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  PhotosRoute: PhotosRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  RosterPlayerIdRoute: RosterPlayerIdRoute,
  TournamentsEventIdRoute: TournamentsEventIdRoute,
  RosterIndexRoute: RosterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
